#!/usr/bin/env bats
# Tests for scripts/harden-compose.sh (Docker Compose security hardening)

load '../helpers/common'

setup() {
    setup_mocks
    
    # Create test deployment directory
    export DEPLOY_DIR="$BATS_TEST_TMPDIR/deploy"
    mkdir -p "$DEPLOY_DIR"
    
    # Create a sample docker-compose.yml with multiple services
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
  
  app:
    image: node:18
    environment:
      - NODE_ENV=production
  
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
EOF

    # Mock commands (not strictly needed for this script, but included for completeness)
    create_mock "docker"
}

teardown() {
    teardown_mocks
}

# ── Argument Validation ───────────────────────────────────────────────────────

@test "harden-compose: fails when no deploy dir provided" {
    run bash "$SCRIPTS_DIR/harden-compose.sh"
    [ "$status" -eq 1 ]
    [[ "$output" =~ "Usage:" ]]
}

@test "harden-compose: shows usage with helpful error on missing directory" {
    run bash "$SCRIPTS_DIR/harden-compose.sh"
    [ "$status" -eq 1 ]
    [[ "$output" =~ "<deploy-dir>" ]]
    [[ "$output" =~ "docker-compose.yml" ]]
}

@test "harden-compose: fails when docker-compose.yml does not exist" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$BATS_TEST_TMPDIR/nonexistent"
    [ "$status" -eq 1 ]
    [[ "$output" =~ "No docker-compose.yml found" ]]
}

@test "harden-compose: rejects unknown option flags" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --unknown-flag
    [ "$status" -eq 1 ]
    [[ "$output" =~ "Unknown option: --unknown-flag" ]]
}

# ── docker-compose.override.yml Generation ────────────────────────────────────

@test "harden-compose: creates docker-compose.override.yml" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    assert_file_exists "$DEPLOY_DIR/docker-compose.override.yml"
}

@test "harden-compose: override file contains YAML header comment" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "# Docker Compose security override"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "# Generated by harden-compose.sh"
}

@test "harden-compose: override file includes CIS compliance reference" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "CIS Docker Benchmark"
}

@test "harden-compose: override file has valid YAML structure with services block" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "services:"
}

# ── Service Detection ─────────────────────────────────────────────────────────

@test "harden-compose: detects all services from docker-compose.yml" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Found services: web app db" ]]
}

@test "harden-compose: generates override for all detected services" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  web:"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  app:"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  db:"
}

@test "harden-compose: handles single-service compose file" {
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
services:
  solo:
    image: alpine:latest
EOF

    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  solo:"
    refute_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  web:"
}

@test "harden-compose: fails gracefully when no services found" {
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
version: '3.8'
volumes:
  data:
EOF

    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --force
    [ "$status" -eq 1 ]
    [[ "$output" =~ "No services found" ]]
}

# ── cap_drop: [ALL] Configuration ─────────────────────────────────────────────

@test "harden-compose: applies cap_drop ALL to all services" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    local override="$DEPLOY_DIR/docker-compose.override.yml"
    
    # Each service should have cap_drop with ALL
    assert_file_contains "$override" "cap_drop:"
    assert_file_contains "$override" "- ALL"
    
    # Count occurrences - should match number of services (3 in this case)
    local count=$(grep -c "cap_drop:" "$override")
    [ "$count" -eq 3 ]
}

@test "harden-compose: cap_drop is properly indented under service name" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    # Verify proper YAML indentation (4 spaces for cap_drop under service)
    grep -A1 "  web:" "$DEPLOY_DIR/docker-compose.override.yml" | grep "    cap_drop:"
}

# ── security_opt: [no-new-privileges:true] ────────────────────────────────────

@test "harden-compose: applies no-new-privileges security option to all services" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    local override="$DEPLOY_DIR/docker-compose.override.yml"
    
    assert_file_contains "$override" "security_opt:"
    assert_file_contains "$override" "- no-new-privileges:true"
    
    # Count occurrences - should match number of services
    local count=$(grep -c "security_opt:" "$override")
    [ "$count" -eq 3 ]
}

@test "harden-compose: security_opt is properly formatted" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    # Verify exact formatting with proper YAML indentation
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "    security_opt:"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "      - no-new-privileges:true"
}

# ── Read-only Mode and tmpfs Mounts ───────────────────────────────────────────

@test "harden-compose: --read-only flag adds read_only: true to services" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    
    local override="$DEPLOY_DIR/docker-compose.override.yml"
    
    assert_file_contains "$override" "read_only: true"
    
    # Count occurrences - should match number of services
    local count=$(grep -c "read_only: true" "$override")
    [ "$count" -eq 3 ]
}

@test "harden-compose: --read-only adds tmpfs mount for /tmp" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "tmpfs:"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "- /tmp:mode=1777,size=64m"
}

@test "harden-compose: --read-only adds tmpfs mount for /run" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "- /run:mode=755,size=32m"
}

@test "harden-compose: --read-only shows warning about testing requirements" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    [ "$status" -eq 0 ]
    [[ "$output" =~ "WARN" ]]
    [[ "$output" =~ "Test thoroughly" ]]
}

@test "harden-compose: without --read-only, does not add read_only setting" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    refute_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "read_only:"
    refute_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "tmpfs:"
}

@test "harden-compose: tmpfs mounts have correct permissions and sizes" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    
    local override="$DEPLOY_DIR/docker-compose.override.yml"
    
    # /tmp should be world-writable (mode=1777) with 64m
    assert_file_contains "$override" "/tmp:mode=1777,size=64m"
    
    # /run should be rwxr-xr-x (mode=755) with 32m
    assert_file_contains "$override" "/run:mode=755,size=32m"
}

# ── Preserves Existing Overrides (--force Flag) ───────────────────────────────

@test "harden-compose: does not overwrite existing override file by default" {
    # Create initial override
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    # Add marker to prove it's the original
    echo "# MARKER" >> "$DEPLOY_DIR/docker-compose.override.yml"
    
    # Run again without --force
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    
    # Original marker should still exist
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "# MARKER"
    
    # Should inform user about existing file
    [[ "$output" =~ "already exists" ]]
    [[ "$output" =~ "--force" ]]
}

@test "harden-compose: --force overwrites existing override file" {
    # Create initial override
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    echo "# MARKER" >> "$DEPLOY_DIR/docker-compose.override.yml"
    
    # Run with --force
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --force
    
    # Marker should be gone (file regenerated)
    refute_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "# MARKER"
    
    # But security settings should still be present
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "cap_drop:"
}

@test "harden-compose: informs user when skipping due to existing file" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Override file already exists" ]]
    [[ "$output" =~ "Use --force to regenerate" ]]
}

# ── Idempotency ───────────────────────────────────────────────────────────────

@test "harden-compose: produces identical output when run twice with --force" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --force
    local first_checksum=$(sha256sum "$DEPLOY_DIR/docker-compose.override.yml" | cut -d' ' -f1)
    
    sleep 0.1  # Ensure different timestamps if timestamps were included
    
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --force
    local second_checksum=$(sha256sum "$DEPLOY_DIR/docker-compose.override.yml" | cut -d' ' -f1)
    
    [ "$first_checksum" = "$second_checksum" ]
}

@test "harden-compose: --read-only produces consistent output across runs" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only --force
    local first_checksum=$(sha256sum "$DEPLOY_DIR/docker-compose.override.yml" | cut -d' ' -f1)
    
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only --force
    local second_checksum=$(sha256sum "$DEPLOY_DIR/docker-compose.override.yml" | cut -d' ' -f1)
    
    [ "$first_checksum" = "$second_checksum" ]
}

# ── Output Messages and User Guidance ─────────────────────────────────────────

@test "harden-compose: confirms successful generation" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Written:" ]]
    [[ "$output" =~ "docker-compose.override.yml" ]]
}

@test "harden-compose: informs user about automatic merge behavior" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "takes effect on next 'docker compose up'" ]]
}

@test "harden-compose: suggests verification command" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "docker compose" ]]
    [[ "$output" =~ "config" ]]
}

@test "harden-compose: with --read-only, provides guidance on volume mounts" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    [ "$status" -eq 0 ]
    [[ "$output" =~ "add explicit volume mounts" ]]
    [[ "$output" =~ "volumes:" ]]
}

# ── Flag Combinations ─────────────────────────────────────────────────────────

@test "harden-compose: accepts both --read-only and --force together" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only --force
    [ "$status" -eq 0 ]
    
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "read_only: true"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "tmpfs:"
}

@test "harden-compose: flag order does not matter" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" --force "$DEPLOY_DIR" --read-only
    [ "$status" -eq 0 ]
    
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "read_only: true"
}

@test "harden-compose: deploy dir can be specified before flags" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only --force
    [ "$status" -eq 0 ]
    assert_file_exists "$DEPLOY_DIR/docker-compose.override.yml"
}

@test "harden-compose: deploy dir can be specified after flags" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" --read-only --force "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    assert_file_exists "$DEPLOY_DIR/docker-compose.override.yml"
}

# ── Edge Cases and Special Scenarios ──────────────────────────────────────────

@test "harden-compose: handles services with hyphens in name" {
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
services:
  my-web-app:
    image: nginx:alpine
  
  api-gateway:
    image: node:18
EOF

    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  my-web-app:"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  api-gateway:"
}

@test "harden-compose: handles services with underscores in name" {
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
services:
  my_service:
    image: alpine:latest
EOF

    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  my_service:"
}

@test "harden-compose: handles compose file with volumes and networks sections" {
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
services:
  web:
    image: nginx:alpine

volumes:
  data:
    driver: local

networks:
  frontend:
  backend:
EOF

    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    
    # Should only process services, not volumes or networks
    assert_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  web:"
    refute_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  data:"
    refute_file_contains "$DEPLOY_DIR/docker-compose.override.yml" "  frontend:"
}

@test "harden-compose: handles relative deploy directory path" {
    cd "$BATS_TEST_TMPDIR"
    
    run bash "$SCRIPTS_DIR/harden-compose.sh" "./deploy"
    [ "$status" -eq 0 ]
    assert_file_exists "$DEPLOY_DIR/docker-compose.override.yml"
}

@test "harden-compose: handles absolute deploy directory path" {
    run bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    [ "$status" -eq 0 ]
    assert_file_exists "$DEPLOY_DIR/docker-compose.override.yml"
}

# ── Complete Override File Structure Validation ───────────────────────────────

@test "harden-compose: generated override has correct complete structure for one service" {
    cat > "$DEPLOY_DIR/docker-compose.yml" <<'EOF'
services:
  test:
    image: alpine:latest
EOF

    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR" --read-only
    
    local override="$DEPLOY_DIR/docker-compose.override.yml"
    
    # Verify complete structure in order
    assert_file_contains "$override" "services:"
    assert_file_contains "$override" "  test:"
    assert_file_contains "$override" "    cap_drop:"
    assert_file_contains "$override" "      - ALL"
    assert_file_contains "$override" "    security_opt:"
    assert_file_contains "$override" "      - no-new-privileges:true"
    assert_file_contains "$override" "    read_only: true"
    assert_file_contains "$override" "    tmpfs:"
    assert_file_contains "$override" "      - /tmp:mode=1777,size=64m"
    assert_file_contains "$override" "      - /run:mode=755,size=32m"
}

@test "harden-compose: each service gets complete security config" {
    bash "$SCRIPTS_DIR/harden-compose.sh" "$DEPLOY_DIR"
    
    local override="$DEPLOY_DIR/docker-compose.override.yml"
    
    # Each of the 3 services should have both cap_drop and security_opt
    local cap_drop_count=$(grep -c "cap_drop:" "$override")
    local security_opt_count=$(grep -c "security_opt:" "$override")
    
    [ "$cap_drop_count" -eq 3 ]
    [ "$security_opt_count" -eq 3 ]
}
