#!/usr/bin/env bats
# Tests for scripts/harden-kernel.sh
# Validates kernel sysctl hardening configuration

load '../helpers/common'

setup() {
    setup_mocks
    
    # Override sysctl.d directory to test location
    export SYSCTL_DIR="$BATS_TEST_TMPDIR/etc/sysctl.d"
    mkdir -p "$SYSCTL_DIR"
    
    # Mock sysctl command to capture and validate calls
    SYSCTL_LOG="$BATS_TEST_TMPDIR/sysctl.log"
    create_mock_with_body "sysctl" "
        echo \"\$*\" >> \"$SYSCTL_LOG\"
        # Return sample values for verification queries
        case \"\$*\" in
            *randomize_va_space*) echo '2' ;;
            *tcp_syncookies*) echo '1' ;;
            *ip_forward*) echo '1' ;;
            *rp_filter*) echo '1' ;;
            *ptrace_scope*) echo '1' ;;
            *) exit 0 ;;
        esac
    "
    
    # Stub cat to write to our test location
    create_mock_with_body "cat" '
        if [[ "$1" == ">" && "$2" == /etc/sysctl.d/* ]]; then
            # Redirect to test location
            target="${2#/etc/sysctl.d/}"
            cat > "'"$SYSCTL_DIR"'/$target"
        else
            /bin/cat "$@"
        fi
    '
}

teardown() {
    teardown_mocks
}

# ── sysctl.d file generation ──────────────────────────────────────────────────

@test "harden-kernel: creates 99-security.conf in sysctl.d" {
    # Modify script to use our SYSCTL_DIR
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    assert_file_exists "$SYSCTL_DIR/99-security.conf"
}

@test "harden-kernel: config file has correct header" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Kernel Hardening Configuration"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Generated by dockerHosting security hardening"
}

@test "harden-kernel: config file is valid conf syntax (no HEREDOC markers)" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    refute_file_contains "$SYSCTL_DIR/99-security.conf" "EOF"
    refute_file_contains "$SYSCTL_DIR/99-security.conf" "<<'"
}

# ── ASLR settings ─────────────────────────────────────────────────────────────

@test "harden-kernel: sets ASLR to full randomization (value 2)" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.randomize_va_space = 2"
}

@test "harden-kernel: ASLR setting has comment explaining purpose" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Enable ASLR"
}

@test "harden-kernel: verification output confirms ASLR value" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"ASLR:"*"2"* ]]
}

# ── SYN cookie protection ─────────────────────────────────────────────────────

@test "harden-kernel: enables TCP SYN cookies for DDoS protection" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.tcp_syncookies = 1"
}

@test "harden-kernel: SYN cookie setting includes anti-DDoS comment" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Enable TCP SYN Cookie Protection"
}

@test "harden-kernel: verification output confirms SYN cookies enabled" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"TCP SYN Cookies:"*"1"* ]]
}

# ── BPF restrictions ──────────────────────────────────────────────────────────

@test "harden-kernel: disables unprivileged BPF" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.unprivileged_bpf_disabled = 1"
}

@test "harden-kernel: BPF restriction limits to privileged users only" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Restrict BPF to privileged users only"
}

# ── ptrace restrictions ───────────────────────────────────────────────────────

@test "harden-kernel: restricts ptrace scope to prevent cross-process debugging" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.yama.ptrace_scope = 1"
}

@test "harden-kernel: ptrace restriction includes explanatory comment" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Restrict ptrace scope"
}

@test "harden-kernel: verification output confirms ptrace scope" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"Ptrace Scope:"*"1"* ]]
}

# ── IP spoofing protection ────────────────────────────────────────────────────

@test "harden-kernel: enables reverse path filtering (anti-spoofing)" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.conf.all.rp_filter = 1"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.conf.default.rp_filter = 1"
}

@test "harden-kernel: rp_filter includes anti-spoofing comment" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# Enable source address verification (anti-spoofing)"
}

@test "harden-kernel: verification output confirms RP filter enabled" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"RP Filter:"*"1"* ]]
}

@test "harden-kernel: blocks ICMP redirects on all interfaces" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.conf.all.accept_redirects = 0"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.conf.default.accept_redirects = 0"
}

@test "harden-kernel: disables source packet routing (spoofing vector)" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.conf.all.accept_source_route = 0"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv6.conf.all.accept_source_route = 0"
}

@test "harden-kernel: enables logging of suspicious (Martian) packets" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.conf.all.log_martians = 1"
}

# ── idempotency ───────────────────────────────────────────────────────────────

@test "harden-kernel: skips configuration when 99-security.conf already exists" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    # First run
    bash "$test_script"
    
    # Mark the config file with a unique identifier
    echo "# ORIGINAL RUN" >> "$SYSCTL_DIR/99-security.conf"
    
    # Second run should skip
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"already hardened"* ]]
    [[ "$output" == *"skipping"* ]]
    
    # Unique identifier should still be present (file not overwritten)
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# ORIGINAL RUN"
}

@test "harden-kernel: idempotent skip message mentions --force flag" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"--force"* ]]
}

# ── --force flag ──────────────────────────────────────────────────────────────

@test "harden-kernel: --force flag reconfigures even when config exists" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    # First run
    bash "$test_script"
    
    # Mark the config file
    echo "# FIRST RUN" >> "$SYSCTL_DIR/99-security.conf"
    
    # Force reconfiguration
    run bash "$test_script" --force
    [ "$status" -eq 0 ]
    [[ "$output" != *"already hardened"* ]]
    
    # Original marker should be gone (file overwritten)
    refute_file_contains "$SYSCTL_DIR/99-security.conf" "# FIRST RUN"
}

@test "harden-kernel: --force flag can appear anywhere in arguments" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    echo "# MARKER" >> "$SYSCTL_DIR/99-security.conf"
    
    # Force with trailing position
    run bash "$test_script" --force
    [ "$status" -eq 0 ]
    refute_file_contains "$SYSCTL_DIR/99-security.conf" "# MARKER"
}

# ── file permissions ──────────────────────────────────────────────────────────

@test "harden-kernel: generated config is readable by all users" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    
    # Check file is readable (at minimum: owner read)
    [ -r "$SYSCTL_DIR/99-security.conf" ]
}

@test "harden-kernel: generated config is a regular file (not directory/symlink)" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    
    [ -f "$SYSCTL_DIR/99-security.conf" ]
    [ ! -L "$SYSCTL_DIR/99-security.conf" ]
    [ ! -d "$SYSCTL_DIR/99-security.conf" ]
}

# ── comprehensive security coverage ───────────────────────────────────────────

@test "harden-kernel: includes kernel pointer protection (kptr_restrict)" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.kptr_restrict = 2"
}

@test "harden-kernel: restricts dmesg access" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.dmesg_restrict = 1"
}

@test "harden-kernel: restricts performance event access" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.perf_event_paranoid = 3"
}

@test "harden-kernel: disables core dumps for SUID processes" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "fs.suid_dumpable = 0"
}

@test "harden-kernel: protects hard and symbolic links" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "fs.protected_hardlinks = 1"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "fs.protected_symlinks = 1"
}

@test "harden-kernel: protects FIFOs and regular files" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "fs.protected_fifos = 2"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "fs.protected_regular = 2"
}

@test "harden-kernel: restricts unprivileged user namespaces" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "kernel.unprivileged_userns_clone = 0"
}

@test "harden-kernel: enables IP forwarding for Docker" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "net.ipv4.ip_forward = 1"
    assert_file_contains "$SYSCTL_DIR/99-security.conf" "# IP Forwarding (required for Docker)"
}

# ── sysctl application ────────────────────────────────────────────────────────

@test "harden-kernel: invokes sysctl to apply settings" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    
    # Verify sysctl was called with -p flag
    [ -f "$SYSCTL_LOG" ]
    grep -q "\-p" "$SYSCTL_LOG"
}

@test "harden-kernel: sysctl applies the generated config file" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    bash "$test_script"
    
    grep -q "99-security.conf" "$SYSCTL_LOG"
}

# ── output verification ───────────────────────────────────────────────────────

@test "harden-kernel: shows success message on completion" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"Kernel Hardening Complete"* ]]
}

@test "harden-kernel: lists enabled security features in output" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"Address Space Layout Randomization"* ]]
    [[ "$output" == *"TCP SYN Cookie Protection"* ]]
    [[ "$output" == *"anti-spoofing"* ]]
}

@test "harden-kernel: shows verification of critical settings" {
    local test_script="$BATS_TEST_TMPDIR/harden-kernel-test.sh"
    sed "s|/etc/sysctl.d|$SYSCTL_DIR|g" "$SCRIPTS_DIR/harden-kernel.sh" > "$test_script"
    chmod +x "$test_script"
    
    run bash "$test_script"
    [ "$status" -eq 0 ]
    [[ "$output" == *"Verifying critical kernel settings"* ]]
}
