#!/usr/bin/env bats
# Tests for scripts/setup-aide.sh — the generated aide.conf must parse on AIDE 0.18+
# (Debian Trixie ships 0.19). The old syntax made 'aide --init' exit 17 on every host.

load '../helpers/common'

setup() {
    AIDE_CONF="$BATS_TEST_TMPDIR/aide.conf"
    sed -n '/^cat > \/etc\/aide\/aide.conf << .EOF.$/,/^EOF$/p' "$SCRIPTS_DIR/setup-aide.sh" |
        sed '1d;$d' > "$AIDE_CONF"
}

@test "setup-aide: aide.conf heredoc is extracted" {
    assert_file_contains "$AIDE_CONF" "Generated by dockerHosting"
}

@test "setup-aide: uses database_in, not the removed 'database=' keyword" {
    assert_file_contains "$AIDE_CONF" "database_in=file:/var/lib/aide/aide.db"
    run grep -E '^database=' "$AIDE_CONF"
    [ "$status" -eq 1 ]
}

@test "setup-aide: defines no empty rule group" {
    run grep -E '^[A-Za-z_]+ *= *$' "$AIDE_CONF"
    [ "$status" -eq 1 ]
}

@test "setup-aide: uses growing+s, not the deprecated S attribute" {
    run grep -E '^[A-Za-z_]+ *=.*\+S(\+|$)' "$AIDE_CONF"
    [ "$status" -eq 1 ]
}

@test "setup-aide: excludes the Docker containers directory" {
    assert_file_contains "$AIDE_CONF" "!/var/lib/docker/containers"
}

@test "setup-aide: config passes 'aide --config-check' where AIDE is installed" {
    command -v aide > /dev/null || skip "aide not installed"
    run aide --config-check -c "$AIDE_CONF"
    [ "$status" -eq 0 ]
}
