#!/usr/bin/env bats
# Tests for scripts/harden-usb.sh
# Validates USB/removable media device restrictions via kernel module blacklisting

load '../helpers/common'

setup() {
    setup_mocks
    
    # Override modprobe.d directory to test location
    export MODPROBE_DIR="$BATS_TEST_TMPDIR/etc/modprobe.d"
    mkdir -p "$MODPROBE_DIR"
    
    # Mock lsmod to simulate loaded/unloaded module states
    LSMOD_LOG="$BATS_TEST_TMPDIR/lsmod.log"
    create_mock_with_body "lsmod" "
        if [[ -f \"$BATS_TEST_TMPDIR/modules_loaded\" ]]; then
            cat <<'LSMOD_EOF'
Module                  Size  Used by
usb_storage            73728  0
firewire_core         81920  1 firewire_ohci
LSMOD_EOF
        else
            cat <<'LSMOD_EOF'
Module                  Size  Used by
ext4                  786432  1
LSMOD_EOF
        fi
        exit 0
    "
    
    # Mock update-initramfs command
    INITRAMFS_LOG="$BATS_TEST_TMPDIR/initramfs.log"
    create_call_log_mock "update-initramfs" "$INITRAMFS_LOG"
    
    # Mock command to control availability of update-initramfs
    create_mock_with_body "command" "
        if [[ \"\$1\" == \"-v\" && \"\$2\" == \"update-initramfs\" ]]; then
            if [[ -f \"$BATS_TEST_TMPDIR/has_initramfs\" ]]; then
                exit 0
            else
                exit 1
            fi
        fi
        /usr/bin/command \"\$@\"
    "
    
    # Patch the script to use our overridden paths
    HARDEN_USB_SCRIPT="$BATS_TEST_TMPDIR/harden-usb-patched.sh"
    sed \
        -e "s|/etc/modprobe.d|$MODPROBE_DIR|g" \
        "$SCRIPTS_DIR/harden-usb.sh" > "$HARDEN_USB_SCRIPT"
    chmod +x "$HARDEN_USB_SCRIPT"
}

teardown() {
    teardown_mocks
}

# ── modprobe.d file generation ────────────────────────────────────────────────

@test "harden-usb: creates harden-usb.conf in modprobe.d" {
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    assert_file_exists "$MODPROBE_DIR/harden-usb.conf"
}

@test "harden-usb: config file has correct header" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "# USB/removable media kernel module blacklist"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "# Generated by harden-usb.sh"
}

@test "harden-usb: config file references compliance frameworks" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "# CIS Benchmark L2 1.1.x"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "UK Cyber Essentials Plus"
}

@test "harden-usb: config file is valid conf syntax (no HEREDOC markers)" {
    bash "$HARDEN_USB_SCRIPT"
    refute_file_contains "$MODPROBE_DIR/harden-usb.conf" "EOF"
    refute_file_contains "$MODPROBE_DIR/harden-usb.conf" "<<'"
}

# ── USB storage blacklist directives ──────────────────────────────────────────

@test "harden-usb: blacklists usb-storage module" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "blacklist usb-storage"
}

@test "harden-usb: sets usb-storage install to /bin/false" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "install usb-storage /bin/false"
}

@test "harden-usb: usb-storage section has descriptive comment" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "# USB storage devices"
}

# ── FireWire blacklist directives ─────────────────────────────────────────────

@test "harden-usb: blacklists firewire-core module" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "blacklist firewire-core"
}

@test "harden-usb: sets firewire-core install to /bin/false" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "install firewire-core /bin/false"
}

@test "harden-usb: blacklists firewire-ohci module" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "blacklist firewire-ohci"
}

@test "harden-usb: sets firewire-ohci install to /bin/false" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "install firewire-ohci /bin/false"
}

@test "harden-usb: blacklists firewire-sbp2 module" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "blacklist firewire-sbp2"
}

@test "harden-usb: sets firewire-sbp2 install to /bin/false" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "install firewire-sbp2 /bin/false"
}

@test "harden-usb: firewire section mentions DMA bypass risk" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "DMA-capable"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "bypass OS memory protections"
}

# ── Thunderbolt blacklist directives ──────────────────────────────────────────

@test "harden-usb: blacklists thunderbolt module" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "blacklist thunderbolt"
}

@test "harden-usb: sets thunderbolt install to /bin/false" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "install thunderbolt /bin/false"
}

@test "harden-usb: thunderbolt section mentions DMA bypass risk" {
    bash "$HARDEN_USB_SCRIPT"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "# Thunderbolt"
}

# ── initramfs update ──────────────────────────────────────────────────────────

@test "harden-usb: rebuilds initramfs when update-initramfs is available" {
    touch "$BATS_TEST_TMPDIR/has_initramfs"
    bash "$HARDEN_USB_SCRIPT"
    assert_file_exists "$INITRAMFS_LOG"
    assert_file_contains "$INITRAMFS_LOG" "-u"
}

@test "harden-usb: skips initramfs rebuild when update-initramfs is unavailable" {
    # Don't create has_initramfs marker
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    if [[ -f "$INITRAMFS_LOG" ]]; then
        run cat "$INITRAMFS_LOG"
        [ "$status" -eq 0 ]
        [ -z "$output" ]
    fi
}

# ── loaded module detection ───────────────────────────────────────────────────

@test "harden-usb: warns when blacklisted modules are currently loaded" {
    touch "$BATS_TEST_TMPDIR/modules_loaded"
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "modules are currently loaded" ]]
    [[ "$output" =~ "Reboot required" ]]
}

@test "harden-usb: reports clean state when no blacklisted modules are loaded" {
    # Don't create modules_loaded marker
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "No affected modules are currently loaded" ]]
}

# ── idempotency ───────────────────────────────────────────────────────────────

@test "harden-usb: skips configuration when file exists (idempotent)" {
    # First run creates the file
    bash "$HARDEN_USB_SCRIPT"
    assert_file_exists "$MODPROBE_DIR/harden-usb.conf"
    
    # Second run should skip
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "already configured" ]]
    [[ "$output" =~ "Use --force to overwrite" ]]
}

@test "harden-usb: overwrites configuration when --force is used" {
    # First run
    bash "$HARDEN_USB_SCRIPT"
    
    # Modify the file to detect overwrite
    echo "# MODIFIED" >> "$MODPROBE_DIR/harden-usb.conf"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "# MODIFIED"
    
    # Second run with --force should overwrite
    bash "$HARDEN_USB_SCRIPT" --force
    refute_file_contains "$MODPROBE_DIR/harden-usb.conf" "# MODIFIED"
    assert_file_contains "$MODPROBE_DIR/harden-usb.conf" "blacklist usb-storage"
}

@test "harden-usb: idempotent behaviour preserves original file on second run" {
    bash "$HARDEN_USB_SCRIPT"
    
    # Capture original content
    local original
    original="$(cat "$MODPROBE_DIR/harden-usb.conf")"
    
    # Second run
    bash "$HARDEN_USB_SCRIPT"
    
    # Content should be identical (file not rewritten)
    local current
    current="$(cat "$MODPROBE_DIR/harden-usb.conf")"
    [ "$original" = "$current" ]
}

# ── root privilege requirement ────────────────────────────────────────────────

@test "harden-usb: requires root privileges (EUID check)" {
    # Patch script to simulate non-root user
    local nonroot_script="$BATS_TEST_TMPDIR/harden-usb-nonroot.sh"
    sed \
        -e "s|/etc/modprobe.d|$MODPROBE_DIR|g" \
        -e 's/\$EUID/999/g' \
        "$SCRIPTS_DIR/harden-usb.sh" > "$nonroot_script"
    chmod +x "$nonroot_script"
    
    run bash "$nonroot_script"
    [ "$status" -eq 1 ]
    [[ "$output" =~ "must be run as root" ]]
}

# ── completion messages ───────────────────────────────────────────────────────

@test "harden-usb: displays completion message" {
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "USB/removable media hardening complete" ]]
}

@test "harden-usb: clarifies USB keyboards/mice are unaffected" {
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "USB keyboards, mice, and network adapters are unaffected" ]]
    [[ "$output" =~ "Only mass storage, FireWire, and Thunderbolt are blocked" ]]
}

@test "harden-usb: confirms config file location in output" {
    run bash "$HARDEN_USB_SCRIPT"
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Written: $MODPROBE_DIR/harden-usb.conf" ]]
}
