#!/bin/bash
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#############################################
# USB / Removable Media Hardening
#
# Blacklists kernel modules for USB storage, FireWire, and Thunderbolt
# to prevent unauthorised data exfiltration via physical media.
#
# Idempotent — safe to re-run. Use --force to overwrite existing config.
#
# Based on: CIS Benchmark L2 1.1.x, UK Cyber Essentials Plus (Malware Protection)
#############################################

set -euo pipefail

CONF_FILE="/etc/modprobe.d/harden-usb.conf"
FORCE=false

for arg in "$@"; do
    [[ "$arg" == "--force" ]] && FORCE=true
done

if [[ "$EUID" -ne 0 ]]; then
    echo "[ERROR] This script must be run as root"
    exit 1
fi

if [[ -f "$CONF_FILE" ]] && [[ "$FORCE" != true ]]; then
    echo "[INFO] USB hardening already configured ($CONF_FILE). Use --force to overwrite."
    exit 0
fi

echo "[INFO] Blacklisting USB storage, FireWire, and Thunderbolt kernel modules..."

cat > "$CONF_FILE" << 'EOF'
# USB/removable media kernel module blacklist
# Generated by harden-usb.sh
# CIS Benchmark L2 1.1.x / UK Cyber Essentials Plus

# USB storage devices (USB flash drives, external HDDs)
install usb-storage /bin/false
blacklist usb-storage

# FireWire (IEEE 1394) — DMA-capable; can bypass OS memory protections
install firewire-core /bin/false
install firewire-ohci /bin/false
install firewire-sbp2 /bin/false
blacklist firewire-core
blacklist firewire-ohci
blacklist firewire-sbp2

# Thunderbolt — DMA-capable; can bypass OS memory protections
install thunderbolt /bin/false
blacklist thunderbolt
EOF

echo "[INFO] Written: $CONF_FILE"

# Rebuild initramfs so the blacklist takes effect on next boot
if command -v update-initramfs &>/dev/null; then
    echo "[INFO] Rebuilding initramfs..."
    update-initramfs -u
    echo "[INFO] Initramfs updated."
fi

# Warn if any of the modules are currently loaded (requires reboot to unload)
LOADED=()
for mod in usb_storage firewire_core firewire_ohci firewire_sbp2 thunderbolt; do
    if lsmod 2>/dev/null | grep -q "^${mod} "; then
        LOADED+=("$mod")
    fi
done

if [[ ${#LOADED[@]} -gt 0 ]]; then
    echo "[WARN] The following modules are currently loaded and will remain active until reboot:"
    for mod in "${LOADED[@]}"; do
        echo "       - $mod"
    done
    echo "[WARN] Reboot required for blacklist to take full effect."
else
    echo "[INFO] No affected modules are currently loaded."
fi

echo "[INFO] USB/removable media hardening complete."
echo "[INFO] Note: USB keyboards, mice, and network adapters are unaffected."
echo "[INFO]       Only mass storage, FireWire, and Thunderbolt are blocked."
