#!/bin/bash
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#############################################
# Docker Compose Security Hardening
#
# Generates a docker-compose.override.yml that applies security hardening
# to every service in an existing docker-compose.yml without modifying the
# application's own compose file.
#
# Applied to each service:
#   - cap_drop: [ALL]              drop all Linux capabilities
#   - security_opt: no-new-privileges:true
#   - With --read-only: read_only: true + tmpfs for /tmp and /run
#
# Docker Compose automatically merges docker-compose.override.yml when
# running `docker compose up`, so no command changes are required.
#
# Usage:
#   harden-compose.sh <deploy-dir>
#   harden-compose.sh <deploy-dir> --read-only
#   harden-compose.sh <deploy-dir> --force
#
# Based on: CIS Docker Benchmark 5.3–5.4, UK Cyber Essentials Plus
#############################################

set -euo pipefail

DEPLOY_DIR=""
READ_ONLY=false
FORCE=false

for arg in "$@"; do
    case "$arg" in
        --read-only) READ_ONLY=true ;;
        --force)     FORCE=true ;;
        -*)          echo "[ERROR] Unknown option: $arg"; exit 1 ;;
        *)           DEPLOY_DIR="$arg" ;;
    esac
done

if [[ -z "$DEPLOY_DIR" ]]; then
    echo "Usage: $0 <deploy-dir> [--read-only] [--force]"
    echo ""
    echo "  <deploy-dir>   Path to the site's deployment directory containing docker-compose.yml"
    echo "  --read-only    Also set read_only: true with tmpfs for /tmp and /run"
    echo "                 (test carefully — some apps require additional write mounts)"
    echo "  --force        Overwrite existing docker-compose.override.yml"
    exit 1
fi

COMPOSE_FILE="$DEPLOY_DIR/docker-compose.yml"
OVERRIDE_FILE="$DEPLOY_DIR/docker-compose.override.yml"

if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "[ERROR] No docker-compose.yml found at: $COMPOSE_FILE"
    exit 1
fi

if [[ -f "$OVERRIDE_FILE" ]] && [[ "$FORCE" != true ]]; then
    echo "[INFO] Override file already exists: $OVERRIDE_FILE"
    echo "[INFO] Use --force to regenerate."
    exit 0
fi

# Extract service names from the compose file
# Looks for top-level service keys under the `services:` block
extract_services() {
    local file="$1"
    # Match lines indented exactly 2 spaces under `services:` that look like service names
    awk '/^services:/{found=1; next} found && /^  [a-zA-Z]/{print $1} found && /^[^ ]/{found=0}' "$file" \
        | tr -d ':'
}

SERVICES=()
while IFS= read -r svc; do
    [[ -n "$svc" ]] && SERVICES+=("$svc")
done < <(extract_services "$COMPOSE_FILE")

if [[ ${#SERVICES[@]} -eq 0 ]]; then
    echo "[ERROR] No services found in $COMPOSE_FILE"
    echo "[INFO]  Ensure the file has a valid 'services:' block with 2-space-indented service names."
    exit 1
fi

echo "[INFO] Found services: ${SERVICES[*]}"
echo "[INFO] Generating $OVERRIDE_FILE..."

{
    echo "# Docker Compose security override"
    echo "# Generated by harden-compose.sh"
    echo "# Merges automatically with docker-compose.yml on 'docker compose up'"
    echo "# CIS Docker Benchmark 5.3-5.4 / UK Cyber Essentials Plus"
    echo ""
    echo "services:"

    for svc in "${SERVICES[@]}"; do
        echo "  ${svc}:"
        echo "    cap_drop:"
        echo "      - ALL"
        echo "    security_opt:"
        echo "      - no-new-privileges:true"
        if [[ "$READ_ONLY" == true ]]; then
            echo "    read_only: true"
            echo "    tmpfs:"
            echo "      - /tmp:mode=1777,size=64m"
            echo "      - /run:mode=755,size=32m"
        fi
    done
} > "$OVERRIDE_FILE"

echo "[INFO] Written: $OVERRIDE_FILE"

if [[ "$READ_ONLY" == true ]]; then
    echo "[WARN] --read-only was set. Test thoroughly — many apps write outside /tmp and /run."
    echo "[INFO] If a service fails to start, add explicit volume mounts for its write paths:"
    echo "       volumes:"
    echo "         - /path/on/host:/path/in/container"
fi

echo "[INFO] Compose hardening applied. No restart required; takes effect on next 'docker compose up'."
echo "[INFO] Verify with: docker compose -f $COMPOSE_FILE -f $OVERRIDE_FILE config"
