#!/bin/bash

#############################################
# Kernel Hardening Script
#
# Hardens kernel parameters via sysctl
# Based on: ISO 27001 A.12.6.1, NIS Article 16
#############################################

set -e

echo "[INFO] Applying kernel hardening via sysctl..."

# Create sysctl security configuration
cat > /etc/sysctl.d/99-security.conf <<'EOF'
# Kernel Hardening Configuration
# Generated by dockerHosting security hardening
# Based on: ISO 27001, NIS, PCI-DSS best practices

#############################################
# Network Security
#############################################

# IP Forwarding (required for Docker)
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore secure ICMP redirects
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0

# Do not send ICMP redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Ignore ICMP ping requests
net.ipv4.icmp_echo_ignore_all = 0

# Ignore Bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable source address verification (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Log suspicious packets (Martians)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

#############################################
# TCP/IP Stack Hardening
#############################################

# Enable TCP SYN Cookie Protection (anti-DDoS)
net.ipv4.tcp_syncookies = 1

# Increase SYN backlog queue
net.ipv4.tcp_max_syn_backlog = 4096

# TCP timestamps for better performance and PAWS
net.ipv4.tcp_timestamps = 1

# Enable selective acknowledgments
net.ipv4.tcp_sack = 1

# Increase TCP buffer sizes for better performance
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# Increase number of incoming connections backlog
net.core.netdev_max_backlog = 5000
net.core.somaxconn = 1024

# Decrease TIME_WAIT timeout
net.ipv4.tcp_fin_timeout = 15

# Protect against TCP time-wait assassination
net.ipv4.tcp_rfc1337 = 1

#############################################
# Memory Protection
#############################################

# Enable ASLR (Address Space Layout Randomization)
kernel.randomize_va_space = 2

# Restrict access to kernel logs
kernel.dmesg_restrict = 1

# Restrict access to kernel pointers in /proc
kernel.kptr_restrict = 2

# Restrict kernel performance events
kernel.perf_event_paranoid = 3

# Hide kernel symbols
kernel.kptr_restrict = 2

#############################################
# File System Hardening
#############################################

# Increase inotify watches for containers
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512

# Protect hard and symbolic links
fs.protected_hardlinks = 1
fs.protected_symlinks = 1

# Protect FIFOs and regular files
fs.protected_fifos = 2
fs.protected_regular = 2

# Restrict core dumps
kernel.core_uses_pid = 1
fs.suid_dumpable = 0

#############################################
# Security Limits
#############################################

# Restrict ptrace scope (prevents debugging of other processes)
kernel.yama.ptrace_scope = 1

# Restrict unprivileged user namespaces (Docker uses privileged ones)
kernel.unprivileged_userns_clone = 0

# Restrict BPF to privileged users only
kernel.unprivileged_bpf_disabled = 1

# Restrict performance events to privileged users
kernel.perf_event_paranoid = 3

#############################################
# IPv6 Hardening (if not using IPv6, disable it)
#############################################

# Accept Router Advertisements only if forwarding is disabled
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# Disable IPv6 if not needed (uncomment to disable)
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1
# net.ipv6.conf.lo.disable_ipv6 = 1
EOF

echo "[INFO] Created sysctl security configuration: /etc/sysctl.d/99-security.conf"

# Apply sysctl settings
echo "[INFO] Applying sysctl settings..."
sysctl -p /etc/sysctl.d/99-security.conf

# Verify critical settings
echo ""
echo "[INFO] Verifying critical kernel settings..."
echo "  ASLR: $(sysctl -n kernel.randomize_va_space) (should be 2)"
echo "  TCP SYN Cookies: $(sysctl -n net.ipv4.tcp_syncookies) (should be 1)"
echo "  IP Forwarding: $(sysctl -n net.ipv4.ip_forward) (should be 1 for Docker)"
echo "  RP Filter: $(sysctl -n net.ipv4.conf.all.rp_filter) (should be 1)"
echo "  Ptrace Scope: $(sysctl -n kernel.yama.ptrace_scope) (should be 1)"

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] Kernel Hardening Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] Key security features enabled:"
echo "  - Address Space Layout Randomization (ASLR)"
echo "  - TCP SYN Cookie Protection (anti-DDoS)"
echo "  - Source address verification (anti-spoofing)"
echo "  - Kernel pointer/symbol protection"
echo "  - Process debugging restrictions"
echo "  - Core dump restrictions"
echo "  - Hard/symbolic link protections"
echo ""
