#!/bin/bash
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#############################################
# SSH Hardening Script
#
# Hardens SSH configuration following security best practices
# Based on: ISO 27001 A.9.4.2, PCI-DSS 2.3
#############################################

set -e

echo "[INFO] Hardening SSH configuration..."

FORCE=false
IGNORE_PRIVATE_RANGES=false
IGNORE_IPS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)
            FORCE=true
            shift
            ;;
        --ignore-private-ranges)
            IGNORE_PRIVATE_RANGES=true
            shift
            ;;
        --ignore-ip)
            [[ $# -gt 1 ]] || {
                echo "[ERROR] --ignore-ip requires an IP or CIDR" >&2
                exit 2
            }
            IGNORE_IPS+=("$2")
            shift 2
            ;;
        *)
            echo "[ERROR] Unknown argument: $1" >&2
            echo "Usage: $0 [--force] [--ignore-ip <ip-or-cidr>] [--ignore-private-ranges]" >&2
            exit 2
            ;;
    esac
done

if [[ "$FORCE" == false ]] && [[ -f /etc/ssh/sshd_config.d/99-hardening.conf ]]; then
    echo "[INFO] SSH already hardened (/etc/ssh/sshd_config.d/99-hardening.conf exists) — skipping (use --force to reconfigure)"
    exit 0
fi

# Backup original sshd_config
if [ ! -f /etc/ssh/sshd_config.backup ]; then
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup
    echo "[INFO] Backed up original sshd_config to /etc/ssh/sshd_config.backup"
fi

# Create hardening configuration in drop-in directory
mkdir -p /etc/ssh/sshd_config.d

cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# SSH Hardening Configuration
# Generated by dockerHosting security hardening

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM yes

# Cryptography
# Only use strong ciphers, MACs, and key exchange algorithms
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256

# Connection settings
LoginGraceTime 30
MaxAuthTries 3
MaxSessions 5
# Reap dead clients within ~3 minutes (60s × 3 probes).  Default of 0 lets
# half-dead sessions accumulate as sshd-session zombies; combined with
# MaxStartups 10:30:100 (sshd default) and no per-source cap, a single
# misbehaving client can monopolise all 10 unauthenticated slots and lock
# everyone out until the service is restarted.
ClientAliveInterval 60
ClientAliveCountMax 3
# Cap any single source IP (or /24) to 5 of the 10 unauthenticated slots,
# so one burst-y client cannot DoS the listener.
PerSourceMaxStartups 5
PerSourceNetBlockSize 24

# Logging
LogLevel VERBOSE
SyslogFacility AUTH

# Security features
StrictModes yes
IgnoreRhosts yes
HostbasedAuthentication no
PermitUserEnvironment no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
Compression no

# Banner
Banner /etc/ssh/banner.txt
EOF

echo "[INFO] Created SSH hardening configuration: /etc/ssh/sshd_config.d/99-hardening.conf"

# Create SSH banner
cat > /etc/ssh/banner.txt << 'EOF'
**************************************************************************
                        AUTHORIZED ACCESS ONLY
**************************************************************************
This system is for authorized use only. All activity is monitored and
logged. Unauthorized access is prohibited and will be prosecuted to the
fullest extent of the law.
**************************************************************************
EOF

chmod 644 /etc/ssh/banner.txt
echo "[INFO] Created SSH banner: /etc/ssh/banner.txt"

# Test SSH configuration before applying
echo "[INFO] Testing SSH configuration..."
if sshd -t; then
    echo "[INFO] SSH configuration test passed"
else
    echo "[ERROR] SSH configuration test failed!"
    echo "[ERROR] Reverting changes..."
    rm -f /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

# Configure fail2ban SSH jail
if command -v fail2ban-client &> /dev/null; then
    echo "[INFO] Configuring fail2ban for SSH..."

    mkdir -p /etc/fail2ban/jail.d

    cat > /etc/fail2ban/jail.d/sshd.conf << 'EOF'
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
findtime = 600
bantime = 3600
EOF

    echo "[INFO] Created fail2ban SSH jail: /etc/fail2ban/jail.d/sshd.conf"

    # Write a site-wide ignoreip drop-in.  The 00- prefix loads it first;
    # the [DEFAULT] section applies to every jail (sshd, plus any others).
    # The template ships with loopback only (127.0.0.1/8 ::1) — public IPs
    # and RFC1918 ranges are opt-in per host via setup.sh prompts (which
    # pass --ignore-ip / --ignore-private-ranges down to this script) so
    # the dockerHosting repo itself never contains customer-specific IPs.
    IGNORE_LIST=("127.0.0.1/8" "::1")
    if [[ "$IGNORE_PRIVATE_RANGES" == "true" ]]; then
        IGNORE_LIST+=("10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16")
    fi
    for ip in "${IGNORE_IPS[@]}"; do
        IGNORE_LIST+=("$ip")
    done

    cat > /etc/fail2ban/jail.d/00-ignoreip.conf << EOF
# fail2ban site-wide ignoreip — generated by dockerHosting/scripts/harden-ssh.sh
#
# 00- prefix loads this before per-jail files; [DEFAULT] settings apply to
# every jail (sshd, future jails).  Loopback addresses are the only entries
# shipped by default — public IPs and private CIDR ranges are added via
# flags during setup, NOT committed to the repo:
#
#   harden-ssh.sh --ignore-ip <addr-or-cidr>      # repeatable
#   harden-ssh.sh --ignore-private-ranges         # adds 10/8 172.16/12 192.168/16
#
# To add more IPs later, edit this file and run: fail2ban-client reload
[DEFAULT]
ignoreip = ${IGNORE_LIST[*]}
EOF
    chmod 644 /etc/fail2ban/jail.d/00-ignoreip.conf
    echo "[INFO] Created fail2ban ignoreip drop-in: /etc/fail2ban/jail.d/00-ignoreip.conf"
    echo "[INFO] Whitelisted: ${IGNORE_LIST[*]}"

    # Restart fail2ban to apply changes
    systemctl restart fail2ban
    echo "[INFO] Restarted fail2ban service"
fi

# Reload SSH service
echo "[INFO] Reloading SSH service..."
systemctl reload sshd

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] SSH Hardening Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[WARN] IMPORTANT: Before logging out, test SSH access in a NEW terminal!"
echo "[WARN] Key changes applied:"
echo "  - Root login disabled"
echo "  - Password authentication disabled (SSH keys only)"
echo "  - Maximum 3 authentication attempts"
echo "  - Session timeout: 5 minutes of inactivity"
echo "  - fail2ban: 3 failed attempts = 1 hour ban"
echo ""
echo "[INFO] To allow password authentication for specific users, add to /etc/ssh/sshd_config.d/99-hardening.conf:"
echo "  Match User username"
echo "  PasswordAuthentication yes"
echo ""
