#!/bin/bash

#############################################
# AIDE File Integrity Monitoring Setup
#
# Installs and configures AIDE (Advanced Intrusion Detection Environment)
# Monitors critical system files for unauthorized modifications
#
# Based on: ISO 27001 A.12.4.1, PCI-DSS 11.5, CIS Benchmark
#############################################

set -e

echo "[INFO] Setting up AIDE file integrity monitoring..."

# Install AIDE if not present
if ! command -v aide &> /dev/null; then
    echo "[INFO] Installing AIDE..."
    apt-get update
    apt-get install -y aide aide-common
fi

# Backup original aide.conf if it exists
if [ -f /etc/aide/aide.conf ] && [ ! -f /etc/aide/aide.conf.backup ]; then
    cp /etc/aide/aide.conf /etc/aide/aide.conf.backup
    echo "[INFO] Backed up original aide.conf"
fi

# Create optimized AIDE configuration
cat > /etc/aide/aide.conf <<'EOF'
# AIDE Configuration
# Generated by dockerHosting security hardening
# Monitors critical system files for unauthorized changes

# Database paths
database=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new
database_new=file:/var/lib/aide/aide.db.new

# Report URL
report_url=stdout

# Rule definitions
# p: permissions, i: inode, n: number of links, u: user, g: group
# s: size, b: block count, m: mtime, a: atime, c: ctime
# S: check for growing size, md5: MD5 checksum, sha256: SHA256 checksum

# Binaries that should not change
Binlib = p+i+n+u+g+s+b+m+c+md5+sha256

# Configuration files (may change)
ConfFiles = p+i+n+u+g+s+b+m+c+md5+sha256

# Log files (size can grow)
Logs = p+u+g+i+n+S

# Databases (size can grow)
Databases = p+u+g+i+n+S

# Ignore these rules
IgnoreNone =

# System binaries and libraries
/bin Binlib
/sbin Binlib
/usr/bin Binlib
/usr/sbin Binlib
/usr/local/bin Binlib
/usr/local/sbin Binlib
/lib Binlib
/lib64 Binlib
/usr/lib Binlib
/usr/lib64 Binlib

# Boot files
/boot Binlib

# Critical system configuration
/etc ConfFiles

# Ignore frequently changing files in /etc
!/etc/mtab
!/etc/adjtime
!/etc/aliases.db
!/etc/ld.so.cache
!/etc/resolv.conf
!/etc/hosts.deny
!/etc/hosts.allow

# Docker configuration (important!)
/etc/docker ConfFiles
/var/lib/docker/containers IgnoreNone

# SSH configuration
/etc/ssh ConfFiles
/root/.ssh ConfFiles

# PAM and security
/etc/pam.d ConfFiles
/etc/security ConfFiles
/etc/sudoers ConfFiles
/etc/sudoers.d ConfFiles

# Systemd
/etc/systemd ConfFiles
/usr/lib/systemd ConfFiles

# Nginx configuration
/etc/nginx ConfFiles

# SSL certificates
/etc/ssl/dockerhosting ConfFiles
/etc/letsencrypt ConfFiles

# Audit configuration
/etc/audit ConfFiles

# dockerHosting scripts
/opt/dockerHosting Binlib

# Log files (monitor growth but expect changes)
/var/log Logs

# Exclude specific log files that change rapidly
!/var/log/wtmp
!/var/log/btmp
!/var/log/lastlog
!/var/log/faillog
!/var/log/journal
!/var/log/audit/audit.log

# Cron jobs
/etc/cron.d ConfFiles
/etc/cron.daily ConfFiles
/etc/cron.hourly ConfFiles
/etc/cron.monthly ConfFiles
/etc/cron.weekly ConfFiles
/var/spool/cron ConfFiles

# Kernel modules
/lib/modules Binlib

# Ignore temporary and cache directories
!/tmp
!/var/tmp
!/var/cache
!/var/run
!/var/lock
!/proc
!/sys
!/dev
!/run
EOF

echo "[INFO] Created AIDE configuration: /etc/aide/aide.conf"

# Create background initialization script
cat > /tmp/aide-init-background.sh <<'INITEOF'
#!/bin/bash
# Background AIDE database initialization
# This script runs in the background to avoid blocking setup

LOGFILE="/var/log/aide/aide-init.log"
STATUSFILE="/var/log/aide/aide-init.status"

mkdir -p /var/log/aide
chmod 700 /var/log/aide

echo "starting" > "$STATUSFILE"
echo "$(date): Starting AIDE database initialization..." >> "$LOGFILE"

# Run aideinit
if aideinit >> "$LOGFILE" 2>&1; then
    # Move new database to active database
    if [ -f /var/lib/aide/aide.db.new ]; then
        cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
        echo "complete" > "$STATUSFILE"
        echo "$(date): AIDE database initialized successfully" >> "$LOGFILE"

        # Send email notification if msmtp is configured
        if command -v mail &> /dev/null && [ -f /etc/msmtprc ]; then
            echo "AIDE file integrity monitoring database has been initialized successfully on $(hostname)." | \
                mail -s "AIDE Initialization Complete - $(hostname)" root 2>/dev/null || true
        fi
    else
        echo "failed" > "$STATUSFILE"
        echo "$(date): ERROR - Database file not created" >> "$LOGFILE"

        # Send failure email notification if msmtp is configured
        if command -v mail &> /dev/null && [ -f /etc/msmtprc ]; then
            echo "AIDE database initialization failed on $(hostname). Check /var/log/aide/aide-init.log for details." | \
                mail -s "AIDE Initialization Failed - $(hostname)" root 2>/dev/null || true
        fi
    fi
else
    echo "failed" > "$STATUSFILE"
    echo "$(date): ERROR - aideinit command failed" >> "$LOGFILE"

    # Send failure email notification if msmtp is configured
    if command -v mail &> /dev/null && [ -f /etc/msmtprc ]; then
        echo "AIDE initialization command failed on $(hostname). Check /var/log/aide/aide-init.log for details." | \
            mail -s "AIDE Initialization Failed - $(hostname)" root 2>/dev/null || true
    fi
fi

# Cleanup
rm -f /tmp/aide-init-background.sh
INITEOF

chmod +x /tmp/aide-init-background.sh

# Start initialization in background
echo "[INFO] Starting AIDE database initialization in background..."
echo "[INFO] This process will continue after setup completes (typically 5-10 minutes)"
nohup /tmp/aide-init-background.sh >/dev/null 2>&1 &

echo "[INFO] AIDE initialization started (PID: $!)"
echo "[INFO] Check status: aide-init-status"
echo "[INFO] View progress: tail -f /var/log/aide/aide-init.log"

# Create daily AIDE check cron job
cat > /etc/cron.daily/aide-check <<'EOF'
#!/bin/bash
# Daily AIDE integrity check
# Generated by dockerHosting security hardening

# Run AIDE check
/usr/bin/aide --check 2>&1 | tee /var/log/aide/aide-check-$(date +%Y%m%d).log

# Send email if changes detected (optional - configure mail first)
# if [ $? -ne 0 ]; then
#     mail -s "AIDE Alert: File Integrity Changes Detected" root < /var/log/aide/aide-check-$(date +%Y%m%d).log
# fi
EOF

chmod 755 /etc/cron.daily/aide-check
echo "[INFO] Created daily AIDE check: /etc/cron.daily/aide-check"

# Create log directory
mkdir -p /var/log/aide
chmod 700 /var/log/aide

# Create helper script for manual checks
cat > /usr/local/bin/aide-check <<'EOF'
#!/bin/bash
# Manual AIDE integrity check
echo "Running AIDE file integrity check..."
aide --check
EOF

chmod 755 /usr/local/bin/aide-check
echo "[INFO] Created helper script: /usr/local/bin/aide-check"

# Create helper script to update database
cat > /usr/local/bin/aide-update <<'EOF'
#!/bin/bash
# Update AIDE database after authorized changes
echo "Updating AIDE database..."
aide --update
if [ -f /var/lib/aide/aide.db.new ]; then
    cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
    echo "AIDE database updated successfully"
else
    echo "ERROR: Database update failed"
    exit 1
fi
EOF

chmod 755 /usr/local/bin/aide-update
echo "[INFO] Created helper script: /usr/local/bin/aide-update"

# Create helper script to check initialization status
cat > /usr/local/bin/aide-init-status <<'EOF'
#!/bin/bash
# Check AIDE database initialization status

STATUSFILE="/var/log/aide/aide-init.status"
LOGFILE="/var/log/aide/aide-init.log"

if [ ! -f "$STATUSFILE" ]; then
    echo "AIDE initialization status: UNKNOWN (status file not found)"
    echo "This could mean AIDE was initialized before this check script was created."

    # Check if database exists
    if [ -f /var/lib/aide/aide.db ]; then
        echo "AIDE database exists: /var/lib/aide/aide.db"
        echo "Status: COMPLETE"
        exit 0
    else
        echo "AIDE database NOT found: /var/lib/aide/aide.db"
        echo "Status: NOT INITIALIZED"
        exit 1
    fi
fi

STATUS=$(cat "$STATUSFILE")

case "$STATUS" in
    starting)
        echo "AIDE initialization status: IN PROGRESS"
        echo ""
        echo "The AIDE database is still being built. This can take 5-10 minutes."
        echo "To monitor progress:"
        echo "  tail -f $LOGFILE"
        exit 2
        ;;
    complete)
        echo "AIDE initialization status: COMPLETE"
        echo ""
        echo "Database location: /var/lib/aide/aide.db"
        echo "Daily checks scheduled: /etc/cron.daily/aide-check"
        echo ""
        echo "Run manual check: aide-check"
        exit 0
        ;;
    failed)
        echo "AIDE initialization status: FAILED"
        echo ""
        echo "Check the log file for details:"
        echo "  cat $LOGFILE"
        echo ""
        echo "To retry initialization:"
        echo "  sudo aideinit"
        echo "  sudo cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db"
        exit 1
        ;;
    *)
        echo "AIDE initialization status: UNKNOWN ($STATUS)"
        exit 3
        ;;
esac
EOF

chmod 755 /usr/local/bin/aide-init-status
echo "[INFO] Created helper script: /usr/local/bin/aide-init-status"

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] AIDE File Integrity Monitoring Setup Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[WARN] Database initialization is running in the background"
echo "[WARN] This process typically takes 5-10 minutes to complete"
echo ""
echo "[INFO] AIDE will monitor:"
echo "  ✓ System binaries (/bin, /sbin, /usr/bin, /usr/sbin)"
echo "  ✓ System libraries (/lib, /usr/lib)"
echo "  ✓ Boot files (/boot)"
echo "  ✓ System configuration (/etc)"
echo "  ✓ Docker configuration (/etc/docker)"
echo "  ✓ SSH configuration (/etc/ssh)"
echo "  ✓ Nginx configuration (/etc/nginx)"
echo "  ✓ SSL certificates (/etc/ssl, /etc/letsencrypt)"
echo "  ✓ Audit configuration (/etc/audit)"
echo "  ✓ dockerHosting scripts (/opt/dockerHosting)"
echo "  ✓ Cron jobs"
echo ""
echo "[INFO] Scheduled checks:"
echo "  - Daily automatic check: /etc/cron.daily/aide-check"
echo "  - Logs: /var/log/aide/aide-check-YYYYMMDD.log"
echo ""
echo "[INFO] Initialization monitoring:"
echo "  - Check status: aide-init-status"
echo "  - View progress: tail -f /var/log/aide/aide-init.log"
echo "  - Initialization log: /var/log/aide/aide-init.log"
echo ""
echo "[INFO] Manual commands:"
echo "  - Check initialization: aide-init-status"
echo "  - Run integrity check: aide-check (or aide --check)"
echo "  - Update database: aide-update (after authorized changes)"
echo "  - Compare: aide --compare"
echo ""
echo "[WARN] IMPORTANT: After making authorized system changes:"
echo "  1. Run: aide-update"
echo "  2. This prevents false positives on next check"
echo ""
echo "[INFO] Email notifications will be sent when initialization completes"
echo ""
