#!/bin/bash
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#############################################
# SSH Multi-Factor Authentication (TOTP)
#
# Adds an optional TOTP second factor to SSH logins using
# libpam-google-authenticator. After setup each user must run
#   google-authenticator
# to generate their own TOTP seed and QR code.
#
# FIDO2/U2F hardware keys are supported if libpam-u2f is installed
# (requires additional per-user registration — see notes below).
#
# Based on: ISO 27001 A.8.5, NIST SP 800-53 IA-2
#############################################

set -euo pipefail

echo "[INFO] Setting up SSH Multi-Factor Authentication (TOTP)..."

FORCE=false
for arg in "$@"; do [[ "$arg" == "--force" ]] && FORCE=true; done

PAM_SSH_FILE=/etc/pam.d/sshd
SSHD_DROP_IN=/etc/ssh/sshd_config.d/98-mfa.conf

if [[ "$FORCE" == false ]] && [[ -f "$SSHD_DROP_IN" ]]; then
    echo "[INFO] SSH MFA already configured — skipping (use --force to reconfigure)"
    exit 0
fi

# Confirm the operator wants to proceed (MFA requires per-user enrolment)
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  SSH MFA SETUP — IMPORTANT"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  This will require a TOTP code (e.g. Google Authenticator,"
echo "  Authy, or any RFC 6238-compatible app) in addition to SSH"
echo "  keys on EVERY login."
echo ""
echo "  BEFORE this script finishes, each user must run:"
echo "    google-authenticator"
echo "  to generate their TOTP seed.  Users who have NOT done this"
echo "  WILL BE LOCKED OUT."
echo ""
echo "  Recommended: set up on a test account first."
echo ""
read -rp "Continue? (type 'yes' to proceed, anything else to abort) " confirm
echo
if [[ "$confirm" != "yes" ]]; then
    echo "[INFO] SSH MFA setup aborted — no changes made"
    exit 0
fi

# Install libpam-google-authenticator
if ! dpkg -l libpam-google-authenticator &>/dev/null; then
    echo "[INFO] Installing libpam-google-authenticator..."
    apt-get install -y libpam-google-authenticator
fi

# Back up PAM sshd config
if [[ -f "$PAM_SSH_FILE" && ! -f "${PAM_SSH_FILE}.pre-mfa.backup" ]]; then
    cp "$PAM_SSH_FILE" "${PAM_SSH_FILE}.pre-mfa.backup"
    echo "[INFO] Backed up $PAM_SSH_FILE"
fi

# Insert the google-authenticator PAM line right after @include common-auth
# (nullok so users without a TOTP seed can still log in during roll-out;
#  remove 'nullok' once all users are enrolled)
if ! grep -q "pam_google_authenticator" "$PAM_SSH_FILE"; then
    # Add before the first @include line so it runs early in the stack
    sed -i '/^@include common-auth/a auth required pam_google_authenticator.so nullok' "$PAM_SSH_FILE"
    echo "[INFO] Added pam_google_authenticator to $PAM_SSH_FILE"
else
    echo "[INFO] pam_google_authenticator already present in $PAM_SSH_FILE"
fi

# Create SSH drop-in: enable ChallengeResponseAuthentication so PAM can ask for
# the TOTP code, and require both pubkey AND password-interactive (2 factors)
mkdir -p /etc/ssh/sshd_config.d

cat > "$SSHD_DROP_IN" <<'EOF'
# SSH MFA Configuration — generated by dockerHosting security hardening
# Requires TOTP in addition to SSH key (two-factor)

# Re-enable keyboard-interactive so PAM can prompt for the TOTP code
KbdInteractiveAuthentication yes

# Require both public-key AND keyboard-interactive (TOTP)
AuthenticationMethods publickey,keyboard-interactive
EOF

echo "[INFO] Created $SSHD_DROP_IN"

# Validate and reload sshd
echo "[INFO] Testing SSH configuration..."
if sshd -t; then
    echo "[INFO] SSH configuration test passed"
    systemctl reload sshd
    echo "[INFO] sshd reloaded"
else
    echo "[ERROR] SSH configuration test failed — reverting MFA changes"
    rm -f "$SSHD_DROP_IN"
    if [[ -f "${PAM_SSH_FILE}.pre-mfa.backup" ]]; then
        cp "${PAM_SSH_FILE}.pre-mfa.backup" "$PAM_SSH_FILE"
    fi
    exit 1
fi

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] SSH MFA Setup Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[WARN] ─── REQUIRED: ENROL EVERY SUDO USER NOW ───"
echo ""
echo "  Each user who will log in via SSH must run (as that user):"
echo ""
echo "    google-authenticator"
echo ""
echo "  Accept the defaults and scan the QR code with an authenticator app."
echo "  Until a user enrols, the 'nullok' option lets them log in without TOTP."
echo "  Once ALL users are enrolled, remove 'nullok' from $PAM_SSH_FILE."
echo ""
echo "[INFO] Configuration:"
echo "  - Authentication:  SSH key + TOTP (two-factor)"
echo "  - PAM module:      pam_google_authenticator (nullok during roll-out)"
echo "  - SSHD drop-in:    $SSHD_DROP_IN"
echo ""
echo "[INFO] To disable MFA later:"
echo "  rm $SSHD_DROP_IN && systemctl reload sshd"
echo ""
