#!/bin/bash

#############################################
# Automated Security Updates Setup
#
# Configures unattended-upgrades for automatic security patches
# Based on: ISO 27001 A.12.6.1, PCI-DSS 6.2
#############################################

set -e

echo "[INFO] Configuring automated security updates..."

# Install unattended-upgrades if not present
if ! dpkg -l | grep -q unattended-upgrades; then
    echo "[INFO] Installing unattended-upgrades..."
    apt-get update
    apt-get install -y unattended-upgrades apt-listchanges
fi

# Backup original configuration if exists
if [ -f /etc/apt/apt.conf.d/50unattended-upgrades ]; then
    cp /etc/apt/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades.backup.$(date +%Y%m%d)
    echo "[INFO] Backed up existing configuration"
fi

# Configure unattended-upgrades
cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
// Automatic security updates configuration
// Generated by dockerHosting security hardening

Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    // Extended Security Maintenance; doesn't necessarily exist for
    // every release and this system may not have it installed, but if
    // available, the policy for updates is such that unattended-upgrades
    // should also install from here by default.
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
    "${distro_id}:${distro_codename}-updates";
    // Docker repository updates
    "Docker:${distro_codename}";
};

// List of packages to NOT automatically upgrade
Unattended-Upgrade::Package-Blacklist {
    // None currently - all security updates allowed
};

// Do automatic removal of unused kernel packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Do automatic removal of new unused dependencies after the upgrade
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

// Do automatic removal of unused packages after the upgrade
// (equivalent to apt-get autoremove)
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot *WITHOUT CONFIRMATION* if the file
// /var/run/reboot-required is found after the upgrade
Unattended-Upgrade::Automatic-Reboot "false";

// Automatically reboot even if users are logged in
// (Set to true only if you're sure about it)
Unattended-Upgrade::Automatic-Reboot-WithUsers "false";

// If automatic reboot is enabled and needed, reboot at the specific
// time instead of immediately (Format: "hh:mm")
Unattended-Upgrade::Automatic-Reboot-Time "03:00";

// Use apt bandwidth limit feature when fetching packages
// Value in kb/sec
//Unattended-Upgrade::Acquire::http::Dl-Limit "1000";

// Enable logging to syslog
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";

// Send email to this address for problems or packages upgrades
// Leave empty to disable email notifications
Unattended-Upgrade::Mail "root";

// Set this value to "true" to get emails only on errors
Unattended-Upgrade::MailReport "only-on-error";

// Download and install upgrades only on AC power
// (i.e. skip or gracefully stop updates on battery)
Unattended-Upgrade::OnlyOnACPower "false";

// Download and install upgrades only on non-metered connection
// (i.e. skip or gracefully stop updates on a metered connection)
Unattended-Upgrade::Skip-Updates-On-Metered-Connections "false";

// Verbose logging
Unattended-Upgrade::Verbose "false";

// Print debugging information
Unattended-Upgrade::Debug "false";
EOF

echo "[INFO] Created unattended-upgrades configuration: /etc/apt/apt.conf.d/50unattended-upgrades"

# Configure automatic update intervals
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
// Automatic update configuration
// Generated by dockerHosting security hardening

// Enable automatic package list updates (every day)
APT::Periodic::Update-Package-Lists "1";

// Enable automatic download of upgradeable packages (every day)
APT::Periodic::Download-Upgradeable-Packages "1";

// Enable automatic installation of security updates (every day)
APT::Periodic::Unattended-Upgrade "1";

// Enable automatic cleanup of old packages (every week)
APT::Periodic::AutocleanInterval "7";

// Automatically remove unused kernel packages
APT::Periodic::CleanKernelImages "1";
EOF

echo "[INFO] Created auto-upgrades configuration: /etc/apt/apt.conf.d/20auto-upgrades"

# Enable and start unattended-upgrades service
systemctl enable unattended-upgrades
systemctl restart unattended-upgrades

# Verify service is running
if systemctl is-active --quiet unattended-upgrades; then
    echo "[INFO] unattended-upgrades service is running"
else
    echo "[WARN] unattended-upgrades service is not active (may be normal)"
fi

# Test configuration
echo "[INFO] Testing unattended-upgrades configuration..."
if unattended-upgrade --dry-run --debug 2>&1 | tail -n 20; then
    echo "[INFO] Configuration test completed"
fi

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] Automated Security Updates Setup Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] Configuration summary:"
echo "  - Security updates: ENABLED (automatic daily)"
echo "  - Package updates: ENABLED (automatic daily)"
echo "  - Auto-remove old packages: ENABLED (weekly)"
echo "  - Automatic reboot: DISABLED (manual intervention required)"
echo "  - Reboot time: 03:00 (if enabled)"
echo "  - Email notifications: root (errors only)"
echo ""
echo "[INFO] Update schedule:"
echo "  - Daily: Check for and install security updates"
echo "  - Daily: Download available package updates"
echo "  - Weekly: Clean up old packages"
echo ""
echo "[INFO] Useful commands:"
echo "  - Check update status: cat /var/log/unattended-upgrades/unattended-upgrades.log"
echo "  - Manual dry-run: unattended-upgrade --dry-run"
echo "  - Force update check: unattended-upgrade --debug"
echo "  - Check if reboot needed: [ -f /var/run/reboot-required ] && cat /var/run/reboot-required"
echo ""
echo "[WARN] To enable automatic reboots, edit /etc/apt/apt.conf.d/50unattended-upgrades:"
echo "       Unattended-Upgrade::Automatic-Reboot \"true\";"
echo ""
