#!/bin/bash

#############################################
# PAM Password Policy Configuration
#
# Enforces strong password requirements:
# - Minimum length
# - Complexity (uppercase, lowercase, digits, special chars)
# - Password history (prevent reuse)
# - Account lockout after failed attempts
#
# Based on: NIST SP 800-63B, PCI-DSS 8.2, ISO 27001 A.9.4.3
#############################################

set -e

echo "[INFO] Configuring PAM password policy..."

# Backup PAM configuration files
for file in /etc/pam.d/common-password /etc/pam.d/common-auth /etc/security/pwquality.conf; do
    if [ -f "$file" ] && [ ! -f "$file.backup" ]; then
        cp "$file" "$file.backup"
        echo "[INFO] Backed up $file"
    fi
done

# Configure password quality requirements
cat > /etc/security/pwquality.conf <<'EOF'
# Password quality configuration
# Generated by dockerHosting security hardening

# Minimum password length
minlen = 14

# Require at least one digit
dcredit = -1

# Require at least one uppercase character
ucredit = -1

# Require at least one lowercase character
lcredit = -1

# Require at least one special character
ocredit = -1

# Maximum number of consecutive characters of same type
maxrepeat = 3

# Maximum number of consecutive characters from same class
maxclassrepeat = 3

# Check if password contains the username
usercheck = 1

# Reject passwords that are dictionary words
dictcheck = 1

# Enforce for root user as well
enforce_for_root
EOF

echo "[INFO] Created /etc/security/pwquality.conf"

# Update common-password to use pwquality
if ! grep -q "pam_pwquality.so" /etc/pam.d/common-password; then
    # Backup
    cp /etc/pam.d/common-password /etc/pam.d/common-password.$(date +%Y%m%d)

    # Add pwquality before pam_unix
    sed -i '/pam_unix.so/i password    requisite    pam_pwquality.so retry=3' /etc/pam.d/common-password

    echo "[INFO] Added pam_pwquality to common-password"
fi

# Configure password history (prevent reuse of last 5 passwords)
if ! grep -q "remember=5" /etc/pam.d/common-password; then
    sed -i 's/\(pam_unix.so.*\)/\1 remember=5/' /etc/pam.d/common-password
    echo "[INFO] Added password history (remember=5)"
fi

# Configure account lockout after failed attempts
if ! grep -q "pam_faillock.so" /etc/pam.d/common-auth; then
    # Backup
    cp /etc/pam.d/common-auth /etc/pam.d/common-auth.$(date +%Y%m%d)

    # Add faillock before pam_unix
    sed -i '/pam_unix.so/i auth    required    pam_faillock.so preauth silent audit deny=5 unlock_time=900' /etc/pam.d/common-auth
    sed -i '/pam_unix.so/a auth    [default=die]    pam_faillock.so authfail audit deny=5 unlock_time=900' /etc/pam.d/common-auth
    sed -i '/pam_unix.so/a auth    sufficient    pam_faillock.so authsucc audit deny=5 unlock_time=900' /etc/pam.d/common-auth

    echo "[INFO] Added account lockout policy (5 attempts, 15 min lockout)"
fi

# Test PAM configuration
echo "[INFO] Testing PAM configuration..."
if pamtest=$(pam-auth-update --force 2>&1); then
    echo "[INFO] PAM configuration test passed"
else
    echo "[WARN] PAM test output: $pamtest"
fi

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] PAM Password Policy Configuration Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] Password requirements:"
echo "  ✓ Minimum length: 14 characters"
echo "  ✓ Must contain: uppercase, lowercase, digit, special character"
echo "  ✓ Maximum consecutive same characters: 3"
echo "  ✓ Username check: enabled"
echo "  ✓ Dictionary check: enabled"
echo "  ✓ Password history: last 5 passwords remembered"
echo ""
echo "[INFO] Account lockout policy:"
echo "  ✓ Failed attempts: 5 maximum"
echo "  ✓ Lockout duration: 15 minutes (900 seconds)"
echo ""
echo "[INFO] To unlock a locked account:"
echo "  faillock --user <username> --reset"
echo ""
echo "[INFO] To check failed login attempts:"
echo "  faillock --user <username>"
echo ""
