#!/bin/bash

#############################################
# Audit Logging Setup Script
#
# Installs and configures auditd for system auditing
# Based on: ISO 27001 A.12.4.1, PCI-DSS 10.2
#############################################

set -e

echo "[INFO] Setting up audit logging (auditd)..."

# Install auditd and audispd-plugins
echo "[INFO] Installing auditd..."
apt-get update
apt-get install -y auditd audispd-plugins

# Backup original audit rules if they exist
if [ -f /etc/audit/rules.d/audit.rules ]; then
    cp /etc/audit/rules.d/audit.rules /etc/audit/rules.d/audit.rules.backup.$(date +%Y%m%d)
    echo "[INFO] Backed up existing audit rules"
fi

# Create security audit rules
cat > /etc/audit/rules.d/99-security.rules <<'EOF'
# Audit Rules for Security Monitoring
# Generated by dockerHosting security hardening
# Based on: ISO 27001, PCI-DSS, CIS Benchmarks

# Remove any existing rules
-D

# Buffer Size (increase if experiencing audit queue overflows)
-b 8192

# Failure Mode (0=silent 1=printk 2=panic)
-f 1

#############################################
# Monitor User and Group Changes
#############################################
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

#############################################
# Monitor Unauthorized Access Attempts
#############################################
-a always,exit -F arch=b64 -S open,openat,openat2 -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b64 -S open,openat,openat2 -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S open,openat,openat2 -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S open,openat,openat2 -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access

#############################################
# Monitor Privilege Escalation
#############################################
-w /etc/sudoers -p wa -k privilege_escalation
-w /etc/sudoers.d/ -p wa -k privilege_escalation
-w /usr/bin/sudo -p x -k privilege_escalation
-a always,exit -F arch=b64 -S setuid,setgid,setreuid,setregid -F auid>=1000 -F auid!=4294967295 -k privilege_escalation
-a always,exit -F arch=b32 -S setuid,setgid,setreuid,setregid -F auid>=1000 -F auid!=4294967295 -k privilege_escalation

#############################################
# Monitor Authentication Events
#############################################
-w /var/log/faillog -p wa -k authentication
-w /var/log/lastlog -p wa -k authentication
-w /var/log/tallylog -p wa -k authentication

#############################################
# Monitor PAM Configuration Changes
#############################################
-w /etc/pam.d/ -p wa -k pam_config
-w /etc/security/ -p wa -k pam_config

#############################################
# Monitor SSH Configuration Changes
#############################################
-w /etc/ssh/sshd_config -p wa -k sshd_config
-w /etc/ssh/sshd_config.d/ -p wa -k sshd_config

#############################################
# Monitor Network Configuration Changes
#############################################
-w /etc/hosts -p wa -k network_config
-w /etc/hostname -p wa -k network_config
-w /etc/network/ -p wa -k network_config
-w /etc/systemd/network/ -p wa -k network_config
-a always,exit -F arch=b64 -S sethostname,setdomainname -k network_config
-a always,exit -F arch=b32 -S sethostname,setdomainname -k network_config

#############################################
# Monitor System Critical File Changes
#############################################
-w /etc/issue -p wa -k system_config
-w /etc/issue.net -p wa -k system_config
-w /boot/grub/grub.cfg -p wa -k bootloader
-w /etc/systemd/system/ -p wa -k systemd
-w /usr/lib/systemd/system/ -p wa -k systemd

#############################################
# Monitor Kernel Module Loading/Unloading
#############################################
-w /sbin/insmod -p x -k kernel_modules
-w /sbin/rmmod -p x -k kernel_modules
-w /sbin/modprobe -p x -k kernel_modules
-a always,exit -F arch=b64 -S init_module,delete_module -k kernel_modules
-a always,exit -F arch=b32 -S init_module,delete_module -k kernel_modules

#############################################
# Monitor Docker Activities
#############################################
-w /usr/bin/docker -p x -k docker
-w /var/lib/docker/ -p wa -k docker
-w /etc/docker/ -p wa -k docker
-w /usr/lib/systemd/system/docker.service -p wa -k docker
-w /var/run/docker.sock -p wa -k docker_socket

#############################################
# Monitor File Deletion Events
#############################################
-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k file_deletion
-a always,exit -F arch=b32 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k file_deletion

#############################################
# Monitor System Calls
#############################################
# Monitor use of system administration tools
-w /usr/sbin/useradd -p x -k user_management
-w /usr/sbin/userdel -p x -k user_management
-w /usr/sbin/usermod -p x -k user_management
-w /usr/sbin/groupadd -p x -k group_management
-w /usr/sbin/groupdel -p x -k group_management
-w /usr/sbin/groupmod -p x -k group_management

#############################################
# Monitor Suspicious Activities
#############################################
# Monitor 32-bit system calls from 64-bit system
-a always,exit -F arch=b32 -S all -k 32bit_api_usage

# Make configuration immutable (must reboot to change rules)
-e 2
EOF

echo "[INFO] Created audit rules: /etc/audit/rules.d/99-security.rules"

# Configure auditd settings for better performance and retention
cat > /etc/audit/auditd.conf <<'EOF'
# Audit daemon configuration
# Generated by dockerHosting security hardening

# Log file location
log_file = /var/log/audit/audit.log

# Log file rotation
log_format = ENRICHED
log_group = adm
priority_boost = 4
name_format = HOSTNAME
max_log_file = 50
num_logs = 10
max_log_file_action = ROTATE

# Disk space management
space_left = 100
space_left_action = SYSLOG
verify_email = yes
action_mail_acct = root
admin_space_left = 50
admin_space_left_action = SUSPEND
disk_full_action = SUSPEND
disk_error_action = SUSPEND

# Performance
freq = 50
flush = INCREMENTAL_ASYNC
EOF

echo "[INFO] Configured auditd: /etc/audit/auditd.conf"

# Load audit rules
echo "[INFO] Loading audit rules..."
augenrules --load

# Enable and start auditd
echo "[INFO] Enabling and starting auditd service..."
systemctl enable auditd
systemctl restart auditd

# Verify auditd is running
if systemctl is-active --quiet auditd; then
    echo "[INFO] auditd service is running"
else
    echo "[ERROR] auditd service failed to start!"
    exit 1
fi

# Show audit statistics
echo ""
echo "[INFO] Audit statistics:"
auditctl -s

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] Audit Logging Setup Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] Monitoring enabled for:"
echo "  - User and group changes"
echo "  - Privilege escalation attempts"
echo "  - Authentication events"
echo "  - SSH configuration changes"
echo "  - Network configuration changes"
echo "  - Docker operations"
echo "  - File deletion events"
echo "  - Kernel module changes"
echo ""
echo "[INFO] Useful commands:"
echo "  - View audit logs: ausearch -k <key>"
echo "  - Example: ausearch -k docker"
echo "  - Real-time monitoring: ausearch -ts recent"
echo "  - Generate report: aureport"
echo "  - Check audit status: auditctl -s"
echo ""
echo "[WARN] Audit rules are now IMMUTABLE (requires reboot to modify)"
echo ""
