#!/bin/bash

#############################################
# Enhanced fail2ban Configuration
#
# Extends fail2ban protection beyond SSH:
# - Nginx HTTP authentication failures
# - Nginx rate limiting violations
# - Nginx bad bot detection
# - SSL handshake abuse
# - Nginx 4xx errors (scanning attempts)
#
# Based on: Common attack patterns, OWASP guidelines
#############################################

set -e

echo "[INFO] Setting up enhanced fail2ban configuration..."

# Ensure fail2ban is installed
if ! command -v fail2ban-client &> /dev/null; then
    echo "[ERROR] fail2ban is not installed"
    exit 1
fi

# Create custom fail2ban filters directory
mkdir -p /etc/fail2ban/filter.d
mkdir -p /etc/fail2ban/jail.d

# Nginx HTTP Auth failures filter
cat > /etc/fail2ban/filter.d/nginx-http-auth.conf <<'EOF'
# Fail2Ban filter for Nginx HTTP authentication failures
[Definition]
failregex = ^ \[error\] \d+#\d+: \*\d+ user "\S+":? (password mismatch|was not found in), client: <HOST>, server: \S+, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"$
            ^ \[error\] \d+#\d+: \*\d+ no user/password was provided for basic authentication, client: <HOST>, server: \S+, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"$
ignoreregex =
EOF

# Nginx rate limit violations filter
cat > /etc/fail2ban/filter.d/nginx-limit-req.conf <<'EOF'
# Fail2Ban filter for Nginx rate limiting violations
[Definition]
failregex = limiting requests, excess:.* by zone.*client: <HOST>
ignoreregex =
EOF

# Nginx bad bots filter
cat > /etc/fail2ban/filter.d/nginx-badbots.conf <<'EOF'
# Fail2Ban filter for bad bots and scanners
[Definition]
badbots = EmailCollector|WebEMailExtrac|TrackBack/1\.02|sogou music spider|(?:Mozilla/\d+\.\d+ )?Jorgee
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*"(?:%(badbots)s)"$
ignoreregex =
EOF

# Nginx 4xx scanning attempts filter
cat > /etc/fail2ban/filter.d/nginx-4xx.conf <<'EOF'
# Fail2Ban filter for excessive 4xx errors (scanning attempts)
[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*(403|404|444)"
ignoreregex = .*(robots\.txt|favicon\.ico|\.well-known).*
EOF

# Nginx noproxy filter (proxy attempt detection)
cat > /etc/fail2ban/filter.d/nginx-noproxy.conf <<'EOF'
# Fail2Ban filter for proxy abuse attempts
[Definition]
failregex = ^<HOST> -.*GET http.*
ignoreregex =
EOF

echo "[INFO] Created fail2ban filters"

# Create enhanced jail configuration
cat > /etc/fail2ban/jail.d/nginx-enhanced.conf <<'EOF'
# Enhanced fail2ban jails for Nginx
# Generated by dockerHosting security hardening

[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/*error.log
maxretry = 3
findtime = 600
bantime = 3600

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/*error.log
maxretry = 10
findtime = 600
bantime = 7200

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/*access.log
maxretry = 2
findtime = 600
bantime = 86400

[nginx-4xx]
enabled = true
port = http,https
filter = nginx-4xx
logpath = /var/log/nginx/*access.log
maxretry = 20
findtime = 60
bantime = 3600

[nginx-noproxy]
enabled = true
port = http,https
filter = nginx-noproxy
logpath = /var/log/nginx/*access.log
maxretry = 2
findtime = 600
bantime = 86400
EOF

echo "[INFO] Created enhanced jail configuration"

# Update SSH jail with stricter settings (already exists, enhance it)
cat > /etc/fail2ban/jail.d/sshd-enhanced.conf <<'EOF'
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
findtime = 600
bantime = 3600
# Ban persistent attackers for longer
bantime.increment = true
bantime.multipliers = 1 2 4 8 16 32 64
bantime.maxtime = 604800
EOF

echo "[INFO] Enhanced SSH jail configuration"

# Restart fail2ban to apply changes
echo "[INFO] Restarting fail2ban..."
systemctl restart fail2ban

# Wait for fail2ban to start
sleep 2

# Verify fail2ban is running
if systemctl is-active --quiet fail2ban; then
    echo "[INFO] fail2ban restarted successfully"
else
    echo "[ERROR] fail2ban failed to start!"
    echo "[ERROR] Check logs: journalctl -xeu fail2ban"
    exit 1
fi

# Display active jails
echo ""
echo "[INFO] Active fail2ban jails:"
fail2ban-client status

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] fail2ban Enhanced Protection Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] Protection enabled for:"
echo "  ✓ SSH brute-force (3 attempts, 1 hour ban, progressive)"
echo "  ✓ Nginx HTTP auth failures (3 attempts, 1 hour ban)"
echo "  ✓ Nginx rate limiting violations (10 attempts, 2 hour ban)"
echo "  ✓ Bad bots/scanners (2 attempts, 24 hour ban)"
echo "  ✓ Excessive 4xx errors (20 attempts/min, 1 hour ban)"
echo "  ✓ Proxy abuse attempts (2 attempts, 24 hour ban)"
echo ""
echo "[INFO] Ban time escalation (SSH):"
echo "  1st ban: 1 hour"
echo "  2nd ban: 2 hours"
echo "  3rd ban: 4 hours"
echo "  4th ban: 8 hours"
echo "  ... up to 7 days maximum"
echo ""
echo "[INFO] Useful commands:"
echo "  - Check status: fail2ban-client status"
echo "  - Check specific jail: fail2ban-client status nginx-http-auth"
echo "  - List banned IPs: fail2ban-client banned"
echo "  - Unban IP: fail2ban-client unban <ip>"
echo "  - View logs: tail -f /var/log/fail2ban.log"
echo ""
