#!/bin/bash

#############################################
# AIDE File Integrity Monitoring Setup
#
# Installs and configures AIDE (Advanced Intrusion Detection Environment)
# Monitors critical system files for unauthorized modifications
#
# Based on: ISO 27001 A.12.4.1, PCI-DSS 11.5, CIS Benchmark
#############################################

set -e

echo "[INFO] Setting up AIDE file integrity monitoring..."

# Install AIDE if not present
if ! command -v aide &> /dev/null; then
    echo "[INFO] Installing AIDE..."
    apt-get update
    apt-get install -y aide aide-common
fi

# Backup original aide.conf if it exists
if [ -f /etc/aide/aide.conf ] && [ ! -f /etc/aide/aide.conf.backup ]; then
    cp /etc/aide/aide.conf /etc/aide/aide.conf.backup
    echo "[INFO] Backed up original aide.conf"
fi

# Create optimized AIDE configuration
cat > /etc/aide/aide.conf <<'EOF'
# AIDE Configuration
# Generated by dockerHosting security hardening
# Monitors critical system files for unauthorized changes

# Database paths
database=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new
database_new=file:/var/lib/aide/aide.db.new

# Report URL
report_url=stdout

# Rule definitions
# p: permissions, i: inode, n: number of links, u: user, g: group
# s: size, b: block count, m: mtime, a: atime, c: ctime
# S: check for growing size, md5: MD5 checksum, sha256: SHA256 checksum

# Binaries that should not change
Binlib = p+i+n+u+g+s+b+m+c+md5+sha256

# Configuration files (may change)
ConfFiles = p+i+n+u+g+s+b+m+c+md5+sha256

# Log files (size can grow)
Logs = p+u+g+i+n+S

# Databases (size can grow)
Databases = p+u+g+i+n+S

# Ignore these rules
IgnoreNone =

# System binaries and libraries
/bin Binlib
/sbin Binlib
/usr/bin Binlib
/usr/sbin Binlib
/usr/local/bin Binlib
/usr/local/sbin Binlib
/lib Binlib
/lib64 Binlib
/usr/lib Binlib
/usr/lib64 Binlib

# Boot files
/boot Binlib

# Critical system configuration
/etc ConfFiles

# Ignore frequently changing files in /etc
!/etc/mtab
!/etc/adjtime
!/etc/aliases.db
!/etc/ld.so.cache
!/etc/resolv.conf
!/etc/hosts.deny
!/etc/hosts.allow

# Docker configuration (important!)
/etc/docker ConfFiles
/var/lib/docker/containers IgnoreNone

# SSH configuration
/etc/ssh ConfFiles
/root/.ssh ConfFiles

# PAM and security
/etc/pam.d ConfFiles
/etc/security ConfFiles
/etc/sudoers ConfFiles
/etc/sudoers.d ConfFiles

# Systemd
/etc/systemd ConfFiles
/usr/lib/systemd ConfFiles

# Nginx configuration
/etc/nginx ConfFiles

# SSL certificates
/etc/ssl/dockerhosting ConfFiles
/etc/letsencrypt ConfFiles

# Audit configuration
/etc/audit ConfFiles

# dockerHosting scripts
/opt/dockerHosting Binlib

# Log files (monitor growth but expect changes)
/var/log Logs

# Exclude specific log files that change rapidly
!/var/log/wtmp
!/var/log/btmp
!/var/log/lastlog
!/var/log/faillog
!/var/log/journal
!/var/log/audit/audit.log

# Cron jobs
/etc/cron.d ConfFiles
/etc/cron.daily ConfFiles
/etc/cron.hourly ConfFiles
/etc/cron.monthly ConfFiles
/etc/cron.weekly ConfFiles
/var/spool/cron ConfFiles

# Kernel modules
/lib/modules Binlib

# Ignore temporary and cache directories
!/tmp
!/var/tmp
!/var/cache
!/var/run
!/var/lock
!/proc
!/sys
!/dev
!/run
EOF

echo "[INFO] Created AIDE configuration: /etc/aide/aide.conf"

# Initialize AIDE database
echo "[INFO] Initializing AIDE database (this may take a few minutes)..."
aideinit

# Move new database to active database
if [ -f /var/lib/aide/aide.db.new ]; then
    cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
    echo "[INFO] AIDE database initialized successfully"
else
    echo "[ERROR] AIDE database initialization failed!"
    exit 1
fi

# Create daily AIDE check cron job
cat > /etc/cron.daily/aide-check <<'EOF'
#!/bin/bash
# Daily AIDE integrity check
# Generated by dockerHosting security hardening

# Run AIDE check
/usr/bin/aide --check 2>&1 | tee /var/log/aide/aide-check-$(date +%Y%m%d).log

# Send email if changes detected (optional - configure mail first)
# if [ $? -ne 0 ]; then
#     mail -s "AIDE Alert: File Integrity Changes Detected" root < /var/log/aide/aide-check-$(date +%Y%m%d).log
# fi
EOF

chmod 755 /etc/cron.daily/aide-check
echo "[INFO] Created daily AIDE check: /etc/cron.daily/aide-check"

# Create log directory
mkdir -p /var/log/aide
chmod 700 /var/log/aide

# Create helper script for manual checks
cat > /usr/local/bin/aide-check <<'EOF'
#!/bin/bash
# Manual AIDE integrity check
echo "Running AIDE file integrity check..."
aide --check
EOF

chmod 755 /usr/local/bin/aide-check
echo "[INFO] Created helper script: /usr/local/bin/aide-check"

# Create helper script to update database
cat > /usr/local/bin/aide-update <<'EOF'
#!/bin/bash
# Update AIDE database after authorized changes
echo "Updating AIDE database..."
aide --update
if [ -f /var/lib/aide/aide.db.new ]; then
    cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
    echo "AIDE database updated successfully"
else
    echo "ERROR: Database update failed"
    exit 1
fi
EOF

chmod 755 /usr/local/bin/aide-update
echo "[INFO] Created helper script: /usr/local/bin/aide-update"

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] AIDE File Integrity Monitoring Setup Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] AIDE is now monitoring:"
echo "  ✓ System binaries (/bin, /sbin, /usr/bin, /usr/sbin)"
echo "  ✓ System libraries (/lib, /usr/lib)"
echo "  ✓ Boot files (/boot)"
echo "  ✓ System configuration (/etc)"
echo "  ✓ Docker configuration (/etc/docker)"
echo "  ✓ SSH configuration (/etc/ssh)"
echo "  ✓ Nginx configuration (/etc/nginx)"
echo "  ✓ SSL certificates (/etc/ssl, /etc/letsencrypt)"
echo "  ✓ Audit configuration (/etc/audit)"
echo "  ✓ dockerHosting scripts (/opt/dockerHosting)"
echo "  ✓ Cron jobs"
echo ""
echo "[INFO] Scheduled checks:"
echo "  - Daily automatic check: /etc/cron.daily/aide-check"
echo "  - Logs: /var/log/aide/aide-check-YYYYMMDD.log"
echo ""
echo "[INFO] Manual commands:"
echo "  - Run check: aide-check (or aide --check)"
echo "  - Update database: aide-update (after authorized changes)"
echo "  - Compare: aide --compare"
echo ""
echo "[WARN] IMPORTANT: After making authorized system changes:"
echo "  1. Run: aide-update"
echo "  2. This prevents false positives on next check"
echo ""
