#!/bin/bash
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

#############################################
# NTP Hardening (chrony)
#
# Ensures accurate, authenticated time synchronisation.
# Accurate clocks are required for:
#   - TLS certificate validation
#   - Audit log correlation
#   - fail2ban time windows
#
# Based on: ISO 27001 A.8.17, CIS Benchmark 2.2.1.3
#############################################

set -euo pipefail

echo "[INFO] Configuring NTP time synchronisation (chrony)..."

FORCE=false
for arg in "$@"; do [[ "$arg" == "--force" ]] && FORCE=true; done

if [[ "$FORCE" == false ]] && command -v chronyc &>/dev/null && systemctl is-active --quiet chrony 2>/dev/null; then
    echo "[INFO] chrony already running — skipping (use --force to reconfigure)"
    chronyc tracking | head -5
    exit 0
fi

# Stop systemd-timesyncd if running (conflicts with chrony)
if systemctl is-active --quiet systemd-timesyncd 2>/dev/null; then
    echo "[INFO] Stopping systemd-timesyncd (replaced by chrony)..."
    systemctl stop systemd-timesyncd
    systemctl disable systemd-timesyncd
fi

# Install chrony
if ! command -v chronyc &>/dev/null; then
    echo "[INFO] Installing chrony..."
    apt-get install -y chrony
fi

# Backup existing config
if [[ -f /etc/chrony/chrony.conf && ! -f /etc/chrony/chrony.conf.backup ]]; then
    cp /etc/chrony/chrony.conf /etc/chrony/chrony.conf.backup
    echo "[INFO] Backed up original chrony.conf"
fi

# Write hardened chrony configuration
cat > /etc/chrony/chrony.conf <<'EOF'
# chrony configuration — generated by dockerHosting security hardening
# Based on: ISO 27001 A.8.17, CIS Benchmark 2.2.1.3

# Use Debian pool NTP servers (HTTPS-validated pool)
pool 0.debian.pool.ntp.org iburst maxsources 3
pool 1.debian.pool.ntp.org iburst maxsources 3
pool 2.debian.pool.ntp.org iburst maxsources 3
pool 3.debian.pool.ntp.org iburst maxsources 3

# Record the rate at which the system clock gains/loses time
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second
makestep 1.0 3

# Enable kernel synchronisation of the real-time clock (RTC)
rtcsync

# Specify directory for log files
logdir /var/log/chrony

# Log measurements, statistics, and tracking
log measurements statistics tracking

# Limit access to localhost only (no NTP server role)
deny all
allow 127.0.0.1
allow ::1

# Reduce the minimum poll interval so chrony converges faster on first sync
minpoll 6
maxpoll 10

# Require at least 3 sources to agree before trusting a time update
# (prevents a single rogue NTP server from skewing the clock)
minsources 2
EOF

echo "[INFO] Wrote /etc/chrony/chrony.conf"

# Enable and start chrony
# Use the canonical unit name (chrony.service) — chronyd.service is a symlink
# alias on Debian and systemctl enable refuses to operate on linked unit files
systemctl enable chrony
systemctl restart chrony

# Wait briefly for initial sync
sleep 2

# Verify service state
if systemctl is-active --quiet chrony; then
    echo "[INFO] chrony is running"
    chronyc tracking | head -8 || true
else
    echo "[ERROR] chrony failed to start"
    journalctl -xeu chrony --no-pager -n 20
    exit 1
fi

echo ""
echo "[INFO] ════════════════════════════════════════════"
echo "[INFO] NTP Hardening Complete!"
echo "[INFO] ════════════════════════════════════════════"
echo ""
echo "[INFO] Configuration summary:"
echo "  - NTP daemon:          chrony (replaces systemd-timesyncd)"
echo "  - Sources:             Debian pool (4 × 3 servers)"
echo "  - Access control:      localhost only (no server role)"
echo "  - Minimum sources:     2 agreeing sources required"
echo "  - Log:                 /var/log/chrony/"
echo ""
echo "[INFO] Useful commands:"
echo "  - Sync status:         chronyc tracking"
echo "  - Source list:         chronyc sources -v"
echo "  - Force resync:        chronyc makestep"
echo ""
